import { writeFile, readFile } from 'node:fs/promises';
import { getBank, getBankIntegrity } from '../src/data/bankData';

const expected = { A: 683, B: 1143, C: 1282 } as const;
const rules = { A:[40,32,8,30,2400], B:[60,45,15,45,3600], C:[90,70,20,70,5400] } as const;
const answers: Record<string, Record<string,string>> = {};
const versions: Record<string,string> = {};
for (const level of ['A','B','C'] as const) {
  const bank=getBank(level); const ids=new Set<string>();
  if(bank.length!==expected[level]) throw new Error(`${level} count mismatch`);
  answers[level]={};
  for(const q of bank){ if(ids.has(q.id)||!/^[ABCD]+$/.test(q.answerType||'')) throw new Error(`${level} invalid ${q.id}`); ids.add(q.id); answers[level][q.id]=q.answerType; }
  versions[level]=getBankIntegrity(level).sha256;
}
const output=`// AUTO-GENERATED by scripts/generate-answer-key.ts. Do not edit.\nexport const QUESTION_ANSWER_KEY = ${JSON.stringify(answers,null,2)} as const;\nexport const BANK_VERSIONS = ${JSON.stringify(versions,null,2)} as const;\nexport const EXAM_RULES = ${JSON.stringify(Object.fromEntries(Object.entries(rules).map(([level,[total,single,multiple,pass,timeSeconds]])=>[level,{total,single,multiple,pass,timeSeconds}])),null,2)} as const;\n`;
const target='src/server/generated/question-answer-key.ts';
if(process.argv.includes('--check')){const current=await readFile(target,'utf8').catch(()=> '');if(current!==output)throw new Error('question-answer-key.ts is stale; run generate:answer-key');}else{await writeFile(target,output);}
