// @ts-check

/** @typedef {'zh-CN' | 'en-US'} RadioLocale */
/** @typedef {'CN' | 'US' | 'GLOBAL'} RadioMarket */
/** @typedef {'Article' | 'WebApplication'} StructuredDataType */
/** @typedef {{ label: string, url: string }} OfficialSource */
/** @typedef {{ question: string, answer: string }} Faq */
/** @typedef {{ heading: string, paragraphs?: string[], items?: string[] }} ContentSection */
/** @typedef {{ path: string, locale: RadioLocale, market: RadioMarket, title: string, description: string, canonical: string, alternates: Partial<Record<RadioLocale, string>>, lastReviewed: string, structuredDataType: StructuredDataType, h1: string, quickAnswer: string, requirements: string[], steps: string[], sections: ContentSection[], cta: string, ctaHref: string, faq: Faq[], officialSources: OfficialSource[] }} RadioRoute */

export const SITE_ORIGIN = 'https://dronerfdiy.com';
export const SUPPORTED_LOCALES = /** @type {const} */ (['zh-CN', 'en-US']);

const sources = {
  crac: { label: 'CRAC — 中国无线电协会业余无线电分会', url: 'https://www.crac.org.cn/' },
  miit: { label: '工业和信息化部 — 业余无线电台管理办法', url: 'https://wap.miit.gov.cn/jgsj/wgj/bmgz/art/2024/art_d042592aca6f4e3ca9cf51720f09bbc2.html' },
  arrl: { label: 'ARRL — Getting Licensed', url: 'https://www.arrl.org/getting-licensed' },
  ncvec: { label: 'NCVEC — Question Pools and Exam Coordinators', url: 'https://www.ncvec.org/' },
};

const cnFaq = [{ question: '本页能替代官方通知吗？', answer: '不能。学习、能力验证、设台和使用要求均应以主管部门、CRAC 和属地机构的当前信息为准。' }];
const usFaq = [{ question: 'Does this site provide an official US question pool?', answer: 'No. This site provides licensing guidance only. Use current material and exam information from official or recognized sources.' }];

/** @param {Omit<RadioRoute, 'canonical' | 'alternates' | 'lastReviewed'> & { alternates?: Partial<Record<RadioLocale, string>> }} input */
const defineRoute = (input) => ({ canonical: input.path, alternates: input.alternates ?? { [input.locale]: input.path }, lastReviewed: '2026-09-03', ...input });

/** The only indexable Radio Earth URLs. Keep this list shallow and intentional. @type {readonly RadioRoute[]} */
export const radioRoutes = [
  defineRoute({ path: '/radio/', locale: 'en-US', market: 'GLOBAL', structuredDataType: 'WebApplication', title: 'Radio Earth | DroneRF DIY', description: 'Amateur radio licensing guides, China A/B/C learning, and practical study tools.', h1: 'Radio Earth', quickAnswer: 'Choose a licensing or learning path, then confirm current regulatory information with the official source for your market.', requirements: ['Choose the market that applies to your station and exam plan.', 'Treat this site as learning guidance, not authorization to transmit.'], steps: ['Choose China or US licensing guidance.', 'Use the relevant learning page.', 'Verify current official requirements before acting.'], sections: [{ heading: 'Learning paths', items: ['US ham radio license guidance', 'China A/B/C learning', 'Exam preparation and radio tools'] }], cta: 'Explore US ham radio licensing', ctaHref: '/radio/ham-radio-license/', faq: [], officialSources: [] }),
  defineRoute({ path: '/radio/ham-radio-license/', locale: 'en-US', market: 'US', structuredDataType: 'Article', title: 'US Ham Radio License Guide | Radio Earth', description: 'A conservative guide to US amateur radio licensing, official sources, and study planning.', h1: 'US ham radio license guide', quickAnswer: 'Use current information from ARRL, NCVEC, the FCC, and your exam coordinator. This page is a guide and does not include an official US question pool.', requirements: ['Confirm current licensing and exam requirements through official or recognized sources.', 'Use current authorized study material.'], steps: ['Choose a license class.', 'Review official sources.', 'Study current material.', 'Confirm an exam session through a recognized coordinator.'], sections: [{ heading: 'License classes', items: ['Technician', 'General', 'Amateur Extra'] }], cta: 'Start with Technician', ctaHref: '/radio/technician/', faq: usFaq, officialSources: [sources.arrl, sources.ncvec] }),
  defineRoute({ path: '/radio/china-license/', locale: 'zh-CN', market: 'CN', structuredDataType: 'Article', title: '中国业余无线电 A/B/C 类学习指南 | Radio Earth', description: '中国业余无线电 A/B/C 类学习、能力验证信息核对与官方来源入口。', h1: '中国业余无线电 A/B/C 类学习指南', quickAnswer: '能力学习、验证和设置使用电台属于相关但不同的事项；请以 CRAC、工信部及属地主管部门的当前信息为准。', requirements: ['确认适用的当前官方要求。', '不要把学习页面当作行政许可结论。'], steps: ['选择 A、B 或 C 类。', '按知识点学习和练习。', '通过官方渠道核对验证、设台和使用要求。'], sections: [{ heading: '学习入口', items: ['A 类', 'B 类', 'C 类'] }], cta: '选择 A 类学习路径', ctaHref: '/radio/license-a/', faq: cnFaq, officialSources: [sources.crac, sources.miit] }),
  defineRoute({ path: '/radio/exam/', locale: 'zh-CN', market: 'CN', structuredDataType: 'WebApplication', title: '业余无线电考试与复习指南 | Radio Earth', description: '面向中国 A/B/C 类学习的复习方法、模拟练习说明与官方来源。', h1: '业余无线电考试与复习指南', quickAnswer: '按知识模块复习并用练习结果定位薄弱点；正式验证安排和题库版本请以官方当前信息为准。', requirements: ['确认学习资料的版本和来源。', '模拟结果仅供学习反馈。'], steps: ['选择目标等级。', '按主题复习。', '复盘错误知识点。', '核对官方安排。'], sections: [{ heading: '复习原则', paragraphs: ['理解法规、操作、技术和安全知识，而不是只记忆选项。'] }], cta: '查看 A 类学习路径', ctaHref: '/radio/license-a/', faq: cnFaq, officialSources: [sources.crac] }),
  defineRoute({ path: '/radio/tools/', locale: 'zh-CN', market: 'CN', structuredDataType: 'WebApplication', title: '业余无线电学习工具 | Radio Earth', description: '业余无线电术语、频率与天馈学习辅助工具。', h1: '业余无线电学习工具', quickAnswer: '工具用于学习和估算，不能替代设备测量、频率核准、执照或任何官方许可。', requirements: ['核对输入数据与单位。', '发射前以实际设备和官方规则为准。'], steps: ['选择工具。', '输入已核实的数据。', '将输出作为学习参考。'], sections: [{ heading: '工具边界', paragraphs: ['计算结果不构成频率、功率或设台授权。'] }], cta: '返回 Radio Earth 首页', ctaHref: '/radio/', faq: cnFaq, officialSources: [sources.miit] }),
  ...[['technician', 'Technician'], ['general', 'General'], ['extra', 'Amateur Extra']].map(([slug, level]) => defineRoute({ path: `/radio/${slug}/`, locale: 'en-US', market: 'US', structuredDataType: 'Article', title: `${level} Ham Radio License Study Guide | Radio Earth`, description: `A cautious ${level} study guide with US official and recognized reference links.`, h1: `${level} ham radio license study guide`, quickAnswer: `Use current authorized material for the ${level} class and confirm current examination details with an official or recognized source. No US question pool is reproduced here.`, requirements: ['Use current authorized study material.', 'Confirm current exam logistics with a recognized coordinator.'], steps: ['Review the current pathway.', 'Study by topic.', 'Practice with authorized material.', 'Confirm an exam session.'], sections: [{ heading: 'Official-reference first', paragraphs: ['Licensing rules, examination arrangements, and question-pool versions can change.'] }], cta: 'Return to the US license guide', ctaHref: '/radio/ham-radio-license/', faq: usFaq, officialSources: [sources.arrl, sources.ncvec] })),
  ...[['a', 'A'], ['b', 'B'], ['c', 'C']].map(([slug, level]) => defineRoute({ path: `/radio/license-${slug}/`, locale: 'zh-CN', market: 'CN', structuredDataType: 'Article', title: `${level} 类业余无线电学习路径 | Radio Earth`, description: `${level} 类业余无线电操作技术能力学习重点、练习方法与官方信息核对入口。`, h1: `${level} 类业余无线电学习路径`, quickAnswer: `围绕法规、操作、技术和安全建立 ${level} 类学习计划；验证、设台与使用条件应以官方当前信息为准。`, requirements: ['使用当前官方发布或认可的学习材料。', '理解规则和安全内容，不只记忆答案。'], steps: ['梳理知识模块。', '进行分主题练习。', '通过官方渠道确认下一步安排。'], sections: [{ heading: '学习提示', paragraphs: ['资料版本和验证安排可能变化，请在行动前再次核对官方来源。'] }], cta: '返回中国 A/B/C 学习指南', ctaHref: '/radio/china-license/', faq: cnFaq, officialSources: [sources.crac, sources.miit] })),
];
